services:
  myapp:
    build:
      context: .
    ports:
      - "12000:3000"
    volumes:
      - .:/myapp
      - /myapp/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    networks:
      - default
