services:
  # myapp:
  #   build:
  #     context: .
  #   ports:
  #     - "12000:3000"
  #   volumes:
  #     - .:/myapp
  #     - /myapp/node_modules
  #   environment:
  #     - WATCHPACK_POLLING=true
  #   command: sh -c "npm run dev"
  #   networks:
  #     - default
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
